# This is a basic workflow to help you get started with Actions

name: pullRequestDevelop

# Controls when the workflow will run
on:
  pull_request:
    branches: [ develop ]
    
env:
  API_PORT: 3000
  POSTGRES_USER: root
  POSTGRES_PASSWORD: root
  POSTGRES_DB: foodStock

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: build docker containers
        run: docker-compose build
        
      - name: run docker containers
        run: docker-compose up -d
        
      - name: run npm install
        run: |
          cd api
          npm ci
        
      - name: run tests
        run: |
          cd api
          npm run test
